title:            "muuee"
url:              https://muuee.github.io
permalink:        pretty
google_analytics: UA-105294524-1
timezone:         Europe/Rome
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji

