title:            Psm
description:      who is Psm? Phạm Xuân Tiếp là ai.
url:              https://tiep.us
permalink:        pretty
timezone:         America/New_York
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
