title:            "muan.co"
url:              https://muuee.github.io
baseurl:          /
permalink:        pretty
google_analytics: UA-21332781-7
timezone:         Asia/Taipei
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji

