title:            Doanh nghiệp tư nhân Thảo Am
description:      Doanh nghiệp tư nhân Thảo Am, Phạm Xuân Tiếp là ai.HSBC 004143665001 CIMB 00336500201403 Techcombank 19036783796010
url:              https://tiep.us
permalink:        pretty
timezone:         America/New_York
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
